
use MangoJRLibrary
go

insert into Author(
 AuthorName)
values
('A.C. Crispin'),
('Aaron Allston'),
('Adam Bray, Cole Horton, Dorling Kindersley Publishing Staff, Tricia Barr'),
('Adam Christopher'),
('Alan Dean Foster'),
('Alan Mitchell, David More (Illustrator)'),
('Aldo Leopold'),
('Alfred Runte'),
('Andy Stanley'),
('Arthur Koester'),
('Bertrand Russell'),
('Bill Hybels'),
('Bjorn Lomborg'),
('Byron Preiss, Ted Mann, Sean Kelly'),
('C.S. Lewis'),
('Cavan Scott'),
('Cavan Scott, Elsa Charretier (Illustrator)'),
('Charles Darwin'),
('Charles Soule'),
('Christie Golden'),
('Christopher Paolini'),
('Christopher Priest'),
('Cindy Martinusen Coloma'),
('Claudia Gray'),
('Cornelia Funke'),
('Craig Cheetham'),
('Craig Groeschel'),
('D. P Simpson'),
('Dale Brown, Jim DeFelice'),
('Dan Britton, Jimmy Page, Jon Gordon'),
('Dann Spader'),
('Darek Isaacs'),
('Dave Ramsey'),
('David McCullough'),
('David Platt'),
('Dennis Rainey, Barbara Rainey'),
('Dick Staub'),
('DK'),
('Dominic Russo'),
('Donny Cates, Dylan Burnett (Illustrator)'),
('Donny Cates, Geoff Shaw (Illustrator)'),
('Doug Fields, Joshua Griffin'),
('Dr. Randy Guliuzza'),
('Drew Karpyshyn'),
('Edwin Wise'),
('Elaine Cunningham'),
('Elizabeth Hand'),
('Emma Mieko Candon'),
('Frank Peretti'),
('Frederic M. Wheelock, Richard A. Lafleur'),
('G.P. Taylor'),
('Gary Graf'),
('Gary L. Thomas'),
('Geoff Johns, Ethan Van Sciver'),
('Green Patriot Working Group'),
('Greg Keyes'),
('Greg Pak, Raffaele Ienco (Artist)'),
('H. G. Wells, Nicholas Grabowsky'),
('Harper Lee'),
('Helen McClory'),
('Herbert McCabe'),
('Hugh Ross'),
('J.K. Rowling, Mary GrandPré'),
('J.K. Rowling'),
('J.R.R. Tolkien'),
('Jack Cottrell'),
('James Choung'),
('James Dashner'),
('James L. Swanson'),
('James Luceno'),
('Jeanne DuPrau'),
('Jeff Hirsch'),
('Jim Campisano'),
('Jim Carmichel'),
('JohannWyss'),
('John McPhee'),
('John Muir'),
('Johnny Scott'),
('Jon Gordon'),
('Jon Krakauer'),
('Jordan B. Peterson'),
('Joseph W. Meeker'),
('Josh Malerman'),
('Joshua A. Taylor'),
('Jude Watson'),
('Jules Verne'),
('Karen Traviss'),
('Kathy Tyers'),
('Keith Griffin, Alan Grant, Simon Bisley'),
('Kevin J. Anderson'),
('Kevin L. DeYoung'),
('Kieron Gillen'),
('Kyle Idleman'),
('Lee Strobel'),
('Linnie Marsh Wolfe'),
('Mari Sandoz'),
('Matt de la Pena'),
('Matthew Stover'),
('Max Brooks'),
('Max Lucado'),
('Michael A. Stackpole'),
('Michael Crichton'),
('Michael J. Behe'),
('Michael P. Kube-Mcdowell'),
('Michael Reaves'),
('Michael Reaves, Steve Perry'),
('Mike Parker Pearson'),
('Nancy Eileen Muleady-Mecham'),
('Nancy Guthrie'),
('Nathan Tan'),
('Nathaniel Philbrick'),
('Nicholas Sparks'),
('Nintendo'),
('Omi M. Inouye'),
('Orson Scott Card'),
('Patricia C. Wrede'),
('Paul S. Kemp'),
('Paul Scheer, Nick Giovannetti, Gerardo Sandoval (Illustrator)'),
('Rachel Carson'),
('Ralph Waldo Emerson, Henry David Thoreau'),
('Rick Johnson'),
('Rick Riordan'),
('Rick Yancey'),
('Robert Allen'),
('Roger Arrick, Nancy Stevenson'),
('Roland Smith'),
('Ruth Ware'),
('Ryder Windham'),
('S.A. Bodeen'),
('Sadie Robertson, Beth Clark'),
('Sean Williams'),
('Sean Williams, Shane Dix'),
('Shel Silverstein'),
('Shigeru Miyamoto, Eiji Aonuma, Akira Himekawa'),
('Sigmund Freud'),
('Stephen Arterburn, Fred Stoeker'),
('Stephen R. Lawhead'),
('Steve Perry'),
('Susan Beth Pfeffer'),
('Tim Harlow'),
('Timothy Keller'),
('Timothy Zahn'),
('Tom Rath'),
('Tristan Gooley'),
('Troy Denning'),
('Tsugumi Ohba'),
('Various'),
('Veronica Roth'),
('Voronica Whitney-Robinson, Haden Blackman'),
('Walter Jon Williams'),
('Wayne Thomas Batson'),
('William Jarrett'),
('William Lane Craig'),
('William Neil Martin'),
('Wm. Paul Young'),
	('Catherine Steadman'),
	('Edmond Doyle'),
	('Michael Chinery'),
	('Henry Abrams & J.J. Abrams'),
	('Leigh Bardugo')
